### ISSUE TITLE
Jaws Release Progress

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/uitk#187]
Not an exhaust list (most labs feature can be pushed back to next release), but create one to track remaining work before cutting a new release.

## Theme

- [x] Characteristics refactor

## Icons package

- [x] Icon and helper is moved from Core to Icons package #200

## Promote component to core

- [x] Layouts (flex, flow, grid, stack) #141
- (Push back to next release) ~Form controls~
    - Form Field #191 #204
    - Switch (pending move to core) #176
    - Checkbox
    - Input
    - Radio Button #201 
    - Stepped Input
- [x] Card #181 
- [x] Panel #155
- (Push back to next release) ~Pill~ #144 + Move to core
- [x] Tooltip (dep of FormField) #198 

## New Lab features

Refer to #121

## Doc

- Docs for new core component
    - [x] Layout #158
- [x] Storybook navigation structure #171

## Others

- [x] No foundation token used in core component css #186

**Comment by origami-z** [comment]
Released in [v0.2.0](https://github.com/jpmorganchase/uitk/releases?q=0.2.0&expanded=true).
