### ISSUE TITLE
Button

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/uitk#303]
Figma Link: https://www.figma.com/file/uQkaSNPxTxrIdkLhZ4UJnf/Button?t=XaooBQNFfosrPApx-0
___

- [x] Investigate removing active style polyfill
- [x] Remove focus polyfill
- [x] Accessibility Spec
- [x] Interaction Spec
- [x] Documentation
- [ ] Figma Component @bhoppers2008

**Comment by origami-z** [comment]
One bug currently on Button: disabled button still appear to be clickable

**Comment by sion-docs** [comment]
Documentation comments

The following sections from the documentation template are currently missing:
- Accessibility
- Related components

Check documentation structure here https://sites.jpmchase.com/:w:/r/sites/JPMUIToolkit/Shared%20Documents/General/Content/Component%20documentation%20structure.docx?d=w87604b98be2e4f788c2956db5a207ce4&csf=1&web=1&e=xVlX2d

**Comment by Fercas123** [comment]
KO Meeting happened today.
main discussion points were: 

- Wenna will start work on the figma files today
- Polymorphic component behaviour is out of scope for first delivery
Dev tasks:
- docs need to be completed as per @sion-docs comments above
- bug on disabled button to be fixed
- remove patch for *[firefox keydown behaviour inconsistency](https://bugzilla.mozilla.org/show_bug.cgi?id=68851)*
- remove override native behaviour and ignore the difference with enter and space

**Comment by james-nash** [comment]
11/24: Agreement on active state has been reached. Needs to be implemented. WIP
