### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by ZarkoPernar** [jpmorganchase/uitk#319]
Figma Spec: https://www.figma.com/file/ScrvgDtdFxRlN9udevJWLC/Icon
___

- [x] Add dev docs https://github.com/jpmorganchase/uitk/pull/571
- [x] Use new size characteristic https://github.com/jpmorganchase/uitk/pull/564
- [x] Refactor Icon to remove createIcon https://github.com/jpmorganchase/uitk/pull/564

**Comment by origami-z** [comment]
Un-assign myself as I won't be working on this anymore.

The top most missing feature would be size/density changes from design decisions (part of #474)

**Comment by parsakhan21** [comment]
Still trying to understand what needs to be done from design side. 
Dev side - looking over code and see if anything can be refined etc. 
Paul/Wenna scheduled call. - Tuesday.

**Comment by parsakhan21** [comment]
Still trying to understand what needs to be done from design side. 
Dev side - looking over code and see if anything can be refined etc. 
Paul/Wenna scheduled call. - Tuesday.

**Comment by parsakhan21** [comment]
10/25 - had chat with Josh re: tech questions. had chat with wenna, but paul is out so convo still pending. 
PR up - has initial refactor of component - david to include pr link here.

**Comment by wennazhang22** [comment]
Hi @bhoppers2008 @pseys as we have our icon library published already, we assume the "Figma component" action item of this project can be marked as done. thanks!

**Comment by parsakhan21** [comment]
10/26
the Icon should be ready on the **7th of November,** current status is as follows:
 
**Wenna** is working on specs,
**Figma component is done** (TBC with Paul and Ben)
**David** is working on component changes
**Fernanda** working on documentation and testing

**Comment by bhoppers2008** [comment]
@wennazhang22 @pseys Yes. I believe so. 

My only question is whether we should provide a standalone icon component IN ADDITION that allows teams to drop in an icon aligned to toolkit sizes. Something like this: https://www.figma.com/file/iEEDe2mvDyrKpIgwg5pccr/Untitled?node-id=0%3A1

We would use the icon library direct in our own components, but is there a place for a standalone component too?

**Comment by bhoppers2008** [comment]
See what @pseys thinks. It would map to what we _currently_ have [in code](https://748253d6.uitk.pages.dev/?path=/docs/icons-icon--toolkit-icon) (not sure if that's changing relative to the size-density work). Providing a more opinionated icon component for standalone use might not be a bad thing.

**Comment by el-dav** [comment]
Note: there is a PR to add update Icons [here](https://github.com/jpmorganchase/uitk/pull/537) which will also need merging

**Comment by pseys** [comment]
I think there's justification for creating a standalone icon component. Although we shouldn't use it in our other components, there's merit to providing an icon component that includes density, size, and possibly colour variants (e.g. primary, secondary, disabled).

**Comment by el-dav** [comment]
Looking through the codebase there are many locations where we use plain SVGs instead of our Icon component. In the longer term I would imagine we should switch these for our Icon.

Would this work be done now as part of Icon, or when we get to those components?

**Comment by joshwooding** [comment]
> Looking through the codebase there are many locations where we use plain SVGs instead of our Icon component. In the longer term I would imagine we should switch these for our Icon.
> 
> 
> 
> Would this work be done now as part of Icon, or when we get to those components?

I would say part of those components. Unless you see any easy drop in fixes

**Comment by JohannaJoergensen** [comment]
Regroup call scheduled for today to discuss progress - team to update issue post mtg.

**Comment by sion-docs** [comment]
Can someone point me to the design spec in Figma? The link above from Zarko doesn't work for me, is that a permissions thing?

**Comment by origami-z** [comment]
> Can someone point me to the design spec in Figma? The link above from Zarko doesn't work for me, is that a permissions thing?

The link has a typo, try again.
