### ISSUE TITLE
Flex Layout

### ISSUE THREAD

**Issue by JoanaMMoreira** [jpmorganchase/uitk#343]
## Preparation
- [x] Existing defect backlog reviewed/evaluated, prioritized, and selected
- [x] Functional requirements defined: functional test script is defined/written (not coded) and signed off by Dev, Design, ADA and Product leads
- [x] Non-functional requirements defined (e.g. controlled vs. uncontrolled)
- [x] Existing enhancements backlog reviewed/evaluated, prioritized, and selected
- [x] Usability testing plan defined or deemed unnecessary
- [x] Examples needed to properly demonstrate component features are defined and signed off by Dev, Design, ADA and Product leads
## Development
- [x] Component implemented in/ported to TypeScript
- [x] 3rd-party dependencies removed
- [x] JSS converted to CSS
- [x] CSS upgraded to use characteristics
- [x] Selected defects resolved
- [x] Component API finalized
- [x] Necessary refactoring completed
- [x] Selected enhancements added
## Testing
- [x] Functional test script is implemented in Cypress and passes
- [x] Code not covered by the functional test script is identified and reviewed by Dev & Design leads
- [x] QA (v1-2 visual regression) test passes
- [x] Automated Axe tests added and pass
## Examples
- [x] All examples present in TK1 are implemented as stories in Odyssey (ported from BitBucket)
- [x] All examples needed are implemented as stories (either ported from BitBucket or created net new)
## Deployment
- [x] Codemods for migration created and verified
## Reviews/Signoff
- [x] Dev production review
- [x] Design review
- [ ] Product signoff
- [ ] ADA review
##  Documentation
- [x] Dev docs content provided
- [x] TK1→Odyssey migration guide provided
- [ ] Design docs provided
- [x] Consolidated documentation produced by combining dev content, migration guide, and design docs
- [x] Consolidated documentation published on Storybook
- [x] Consolidated documentation reviewed and updated according to user feedback
##  Figma symbols
- [ ] New Odyssey Figma symbol created
- [ ] Figma symbol references updated to use new Figma symbol

**Comment by maj-stella** [comment]
Suggested changes from Jira 9455 has been implemented.

There is only design consideration left about separators. When a. Page is zoomed in and it reflows, separators appear on the right which do not have any function (they do not separate anything) as they are at the end. Please see screenshots below.



![Image](https://user-images.githubusercontent.com/112501956/189363548-6ff2120b-0e70-4155-9b5d-797fb85ee996.png)



![Image](https://user-images.githubusercontent.com/112501956/189363561-4cc3efae-5d34-49ef-80c9-57db74d9828a.png)

**Comment by JoanaMMoreira** [comment]
Hi @maj-stella, I've changed the default wrap value to false as discussed https://flex-layout-nowrap-by-defaul.uitk.pages.dev/?path=/story/core-layout-flexlayout--default-flex-layout

**Comment by Fercas123** [comment]
@maj-stella please see the below link for the changes on responsiveness:
 https://layout-examples-ada-update.uitk.pages.dev/?path=/story/core-layout-flexlayout--default-flex-layout

**Comment by maj-stella** [comment]
I'm signing Flex Layout off; however the following examples 'Flex Layout Simple Usage', Flex Layout Composite' and 'Flex Layout Nested' need to be revisited when components which are used in Flex Layout are developed. Currently those components are not accessible.

Also I recommend design review when separators are used in zoom in 400% screen.
