### ISSUE TITLE
Flow Layout

### ISSUE THREAD

**Issue by JoanaMMoreira** [jpmorganchase/uitk#366]
## Preparation
- [x] Existing defect backlog reviewed/evaluated, prioritized, and selected
- [x] Functional requirements defined: functional test script is defined/written (not coded) and signed off by Dev, Design, ADA and Product leads
- [x] Non-functional requirements defined (e.g. controlled vs. uncontrolled)
- [x] Existing enhancements backlog reviewed/evaluated, prioritized, and selected
- [x] Usability testing plan defined or deemed unnecessary
- [x] Examples needed to properly demonstrate component features are defined and signed off by Dev, Design, ADA and Product leads
## Development
- [x] Component implemented in/ported to TypeScript
- [x] 3rd-party dependencies removed
- [x] JSS converted to CSS
- [x] CSS upgraded to use characteristics
- [x] Selected defects resolved
- [x] Component API finalized
- [x] Necessary refactoring completed
- [x] Selected enhancements added
## Testing
- [x] Functional test script is implemented in Cypress and passes
- [x] Code not covered by the functional test script is identified and reviewed by Dev & Design leads
- [x] QA (v1-2 visual regression) test passes
- [x] Automated Axe tests added and pass
## Examples
- [x] All examples present in TK1 are implemented as stories in Odyssey (ported from BitBucket)
- [x] All examples needed are implemented as stories (either ported from BitBucket or created net new)
## Deployment
- [x] Codemods for migration created and verified
## Reviews/Signoff
- [x] Dev production review
- [x] Design review
- [ ] Product signoff
- [x] ADA review
##  Documentation
- [x] Dev docs content provided
- [x] TK1→Odyssey migration guide provided
- [ ] Design docs provided
- [x] Consolidated documentation produced by combining dev content, migration guide, and design docs
- [x] Consolidated documentation published on Storybook
- [x] Consolidated documentation reviewed and updated according to user feedback
##  Figma symbols
- [ ] New Odyssey Figma symbol created
- [ ] Figma symbol references updated to use new Figma symbol
