### ISSUE TITLE
Border Layout

### ISSUE THREAD

**Issue by JoanaMMoreira** [jpmorganchase/uitk#372]
## Preparation
- [x] Existing defect backlog reviewed/evaluated, prioritized, and selected
- [x] Functional requirements defined: functional test script is defined/written (not coded) and signed off by Dev, Design, ADA and Product leads
- [x] Non-functional requirements defined (e.g. controlled vs. uncontrolled)
- [x] Existing enhancements backlog reviewed/evaluated, prioritized, and selected
- [x] Usability testing plan defined or deemed unnecessary
- [x] Examples needed to properly demonstrate component features are defined and signed off by Dev, Design, ADA and Product leads
## Development
- [x] Component implemented in/ported to TypeScript
- [x] 3rd-party dependencies removed
- [x] JSS converted to CSS
- [x] CSS upgraded to use characteristics
- [x] Selected defects resolved
- [x] Component API finalized
- [x] Necessary refactoring completed
- [x] Selected enhancements added
## Testing
- [x] Functional test script is implemented in Cypress and passes
- [x] Code not covered by the functional test script is identified and reviewed by Dev & Design leads
- [x] QA (v1-2 visual regression) test passes
- [x] Automated Axe tests added and pass
## Examples
- [x] All examples present in TK1 are implemented as stories in Odyssey (ported from BitBucket)
- [x] All examples needed are implemented as stories (either ported from BitBucket or created net new)
## Deployment
- [x] Codemods for migration created and verified
## Reviews/Signoff
- [x] Dev production review
- [x] Design review
- [ ] Product signoff
- [ ] ADA review
##  Documentation
- [ ] Dev docs content provided
- [x] TK1→Odyssey migration guide provided
- [ ] Design docs provided
- [ ] Consolidated documentation produced by combining dev content, migration guide, and design docs
- [x] Consolidated documentation published on Storybook
- [ ] Consolidated documentation reviewed and updated according to user feedback
##  Figma symbols
- [ ] New Odyssey Figma symbol created
- [ ] Figma symbol references updated to use new Figma symbol

**Comment by maj-stella** [comment]
1. The code is generic with <div> elements. <div> element does not have semantic meaning; therefore names header and main in the design might be confusing as resemble semantic elements <header> and <main>. Rename Header and Main. E.g Header=Top, Main= Main section. (Check with Content Designer to find the most appropriate name).
2. For building a website I would suggest to add and option for meaningful semantics so the structure of a document is semantically correct; therefore screen reader users can navigate from section to section.

Top: <header>…</header>
Main section: <main>…</main>
Left: <nav>…</nav> or <aside>…</aside>
Right: <nav>…</nav> or <aside>…</aside>
Bottom: <footer>…</footer>

3. Border Layout Form Composite and Border Layout Form Contacts Composite examples
A Layout component is accessible, however components inside the layout component are not accessible.

**Comment by JoanaMMoreira** [comment]
@maj-stella here you go: https://polymorphic-layout-component-gsek.uitk.pages.dev/?path=/story/core-layout-borderlayout--border-layout-all-panels 

Let me know how that looks :)

**Comment by maj-stella** [comment]
In examples ‘Border Layout Fixed Panel’ and ‘Border Layout Contacts Composite’ there are buttons which are in `<footer>` (first screenshot below). Move buttons to the `<main>` as they are part of the main content and delete `<footer>`. If `<footer>` element needs to be on the page to showcase the structure of the document, put some additional information and links instead. Please see an example of footer in the second screenshot below.

1. Buttons in `<main>`

![Image](https://user-images.githubusercontent.com/112501956/195390135-915ce02c-01ec-42b1-80fd-d25bf03f8fe6.png)

2. Example of content in `<footer>`
![Image](https://user-images.githubusercontent.com/112501956/195390623-58741697-d72e-40ab-8804-124aa84e6711.png)
