### ISSUE TITLE
CSS Fixes and Clean up

### ISSUE THREAD

**Issue by libertymayc** [jpmorganchase/uitk#377]
PRs created for the following (ticked when merged):

- [x]  (#344) Standardise attributes appearing in tokens to always be kebab case, e.g. -border-color -> -borderColor _(lint rule added)_ 
- [x]  (#323) Add min height to text.css help tokens
- [x] (#350) ToggleButton using characteristics: not 100% polished, but ensures lab package passes linting
- [x] (#371) Remove random values in List (e.g. —hw-… : check with @heswell about these) *noting that list/tree etc still require token alignment and so aren’t 100% currently
- [x] (#375) Updates to measured characteristic fill value
- [x] (#376) Remove component name classes when tokens are density dependent (see issue #330 for explanation)
- [x] (#376) Needs fixing: Grid component has special values for ultrahigh density 
- [x] (#380) Ensure component tokens start with their full name, e.g. —doc-grid -> —docGrid _(lint rule added)_
- [x] (#428) (#441) (#456) For backwards compat tokens, standardise by creating —backwardsCompat- token and then set the **local** var token (if exists, else the raw attr) within .backwardsCompat class
- [x] (#297) Needs fixing: Grid component uses API for variables where local property should be used
