### ISSUE TITLE
Grid Layout

### ISSUE THREAD

**Issue by JoanaMMoreira** [jpmorganchase/uitk#396]
## Preparation
- [x] Existing defect backlog reviewed/evaluated, prioritized, and selected
- [x] Functional requirements defined: functional test script is defined/written (not coded) and signed off by Dev, Design, ADA and Product leads
- [x] Non-functional requirements defined (e.g. controlled vs. uncontrolled)
- [x] Existing enhancements backlog reviewed/evaluated, prioritized, and selected
- [x] Usability testing plan defined or deemed unnecessary
- [x] Examples needed to properly demonstrate component features are defined and signed off by Dev, Design, ADA and Product leads
## Development
- [x] Component implemented in/ported to TypeScript
- [x] 3rd-party dependencies removed
- [x] JSS converted to CSS
- [x] CSS upgraded to use characteristics
- [x] Selected defects resolved
- [x] Component API finalized
- [x] Necessary refactoring completed
- [x] Selected enhancements added
## Testing
- [x] Functional test script is implemented in Cypress and passes
- [x] Code not covered by the functional test script is identified and reviewed by Dev & Design leads
- [x] QA (v1-2 visual regression) test passes
- [x] Automated Axe tests added and pass
## Examples
- [x] All examples present in TK1 are implemented as stories in Odyssey (ported from BitBucket)
- [x] All examples needed are implemented as stories (either ported from BitBucket or created net new)
## Deployment
- [x] Codemods for migration created and verified
## Reviews/Signoff
- [x] Dev production review
- [x] Design review
- [ ] Product signoff
- [ ] ADA review
##  Documentation
- [ ] Dev docs content provided
- [ ] TK1→Odyssey migration guide provided
- [ ] Design docs provided
- [ ] Consolidated documentation produced by combining dev content, migration guide, and design docs
- [ ] Consolidated documentation published on Storybook
- [ ] Consolidated documentation reviewed and updated according to user feedback
##  Figma symbols
- [ ] New Odyssey Figma symbol created
- [ ] Figma symbol references updated to use new Figma symbol

**Comment by maj-stella** [comment]
Grid Layout examples don’t pass WCAG 2.1 guidelines 1.4.10 Reflow :

https://www.w3.org/WAI/WCAG21/Understanding/reflow.html

Also when Grid Layout Responsive View is zoomed in to 125%, re-ordered columns would cause an issue for keyboard users if they are tabbing through interactive elements. E.g Focus would go from the bottom right to the middle left which is confusing. Please see the screenshot below.



![Image](https://user-images.githubusercontent.com/112501956/192824973-ef2bd70d-fd61-43e9-8b12-e29c62bd3a91.png)

**Comment by parsakhan21** [comment]
12/6

- starting on this today 
- Mainly changing two issues - examples to be accessible etc
