### ISSUE TITLE
Text

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/uitk#475]
Figma Spec: https://figma.com/file/qHsmecWdxQ87m70qlk5yMJ/Text

___

- [x] Accessibility spec @navkaur76 
- [x] Interaction spec
- [x] Documentation https://github.com/jpmorganchase/uitk/pull/661
- [x] Simplify Text by removing auto truncation https://github.com/jpmorganchase/uitk/pull/661
- [x] Remove Div, Span, P components https://github.com/jpmorganchase/uitk/pull/661

**Comment by bhoppers2008** [comment]
@parsakhan21 Nav is ready to pick up something new. Text is next in the order (after Status which is probably best to go to Wenna). Is that ok? 
cc' @navkaur76 @pseys

**Comment by parsakhan21** [comment]
Hi Ben, sounds good to me. Just copying Robin in case he has any comments @shinytoyrobots

**Comment by joshwooding** [comment]
Makes sense to me too.

**Comment by parsakhan21** [comment]
11/1 - Nav working on specs; call with Paul/Wenna to clarify questions

**Comment by parsakhan21** [comment]
11/1 - Nav working on specs; call with Paul/Wenna to clarify questions

**Comment by james-nash** [comment]
11/24: Interaction spec & ADA nearing completion
