### ISSUE TITLE
Stack Layout

### ISSUE THREAD

**Issue by JoanaMMoreira** [jpmorganchase/uitk#482]
## Preparation
- [x] Existing defect backlog reviewed/evaluated, prioritized, and selected
- [x] Functional requirements defined: functional test script is defined/written (not coded) and signed off by Dev, Design, ADA and Product leads
- [x] Non-functional requirements defined (e.g. controlled vs. uncontrolled)
- [x] Existing enhancements backlog reviewed/evaluated, prioritized, and selected
- [x] Usability testing plan defined or deemed unnecessary
- [x] Examples needed to properly demonstrate component features are defined and signed off by Dev, Design, ADA and Product leads
## Development
- [x] Component implemented in/ported to TypeScript
- [x] 3rd-party dependencies removed
- [x] JSS converted to CSS
- [x] CSS upgraded to use characteristics
- [x] Selected defects resolved
- [x] Component API finalized
- [x] Necessary refactoring completed
- [x] Selected enhancements added
## Testing
- [x] Functional test script is implemented in Cypress and passes
- [x] Code not covered by the functional test script is identified and reviewed by Dev & Design leads
- [x] QA (v1-2 visual regression) test passes
- [x] Automated Axe tests added and pass
## Examples
- [x] All examples present in TK1 are implemented as stories in Odyssey (ported from BitBucket)
- [x] All examples needed are implemented as stories (either ported from BitBucket or created net new)
## Deployment
- [x] Codemods for migration created and verified
## Reviews/Signoff
- [x] Dev production review
- [x] Design review
- [ ] Product signoff
- [ ] ADA review
##  Documentation
- [ ] Dev docs content provided
- [x] TK1→Odyssey migration guide provided
- [ ] Design docs provided
- [ ] Consolidated documentation produced by combining dev content, migration guide, and design docs
- [ ] Consolidated documentation published on Storybook
- [ ] Consolidated documentation reviewed and updated according to user feedback
##  Figma symbols
- [ ] New Odyssey Figma symbol created
- [ ] Figma symbol references updated to use new Figma symbol

**Comment by Fercas123** [comment]
@maj-stella please see the below link for the stack stories:
default: https://layout-examples-ada-update.uitk.pages.dev/?path=/story/core-layout-stacklayout--default-stack-layout
simple: https://layout-examples-ada-update.uitk.pages.dev/?path=/story/core-layout-stacklayout--stack-layout-simple-usage
composite: https://layout-examples-ada-update.uitk.pages.dev/?path=/story/core-layout-stacklayout--stack-layout-composite

**Comment by maj-stella** [comment]
I'm signing Stack component off; however 'Stack Layout Composite' needs to be revisited when FormField component is developed. Stack Layout Composite example is using FormField which is not compliant at the current time.

<img width="489" alt="Screenshot 2022-10-14 at 11 24 38" src="https://user-images.githubusercontent.com/112501956/195832738-96c22559-98cb-443d-a32d-a81c142fa192.png">
